# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: coffeemate-app # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      database:
        image: postgres
        env:
          POSTGRES_USER: coffeemate_user
          POSTGRES_PASSWORD: coffeemate_password
          POSTGRES_DB: coffeemate_tst
        ports:
          - 25432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.3'
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
        env:
          DATABASE_URL: "postgres://coffeemate_user:coffeemate_password@localhost:25432"
          RAILS_ENV: test
      - name: Building web app
        uses: azure/appservice-build@v2
      - name: Deploy web App using GH Action azure/webapps-deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
