# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: masa-iwasaki/setup-rbenv@v1
      - name: Cache RBENV_ROOT
        uses: actions/cache@v1
        id: cache_rbenv
        with:
          path: /home/runner/.rbenv
          key: ${{ runner.os }}-rbenv-${{ hashFiles('**/.ruby-version') }}
          restore-keys: |
            {{ runner.os }}-rbenv-
      - name: Install Ruby
        run: |
          eval "$(rbenv init -)"
          rbenv install -s `cat .ruby-version` # or specify the version you want
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
